.\" Copyright (C) 2025-2026 alx@fastestcode.org
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.\" EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
.\" CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
.\" TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
.\" SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.Dd June 24, 2026
.Dt X11DND_GET_AWARE_VERSION 3
.Os
.Sh NAME
.Nm x11dnd_get_aware_version
.Nd read the XdndAware version of a window
.Sh LIBRARY
.Lb libx11dnd
.Sh SYNOPSIS
.In x11dnd.h
.Ft int
.Fn x11dnd_get_aware_version "Display *dpy" "Window win"
.Sh DESCRIPTION
.Fn x11dnd_get_aware_version
reads the
.Li XdndAware
property of
.Fa win
and returns the XDnD version advertised by that window.
.Sh RETURN VALUES
Returns the XDnD protocol version (a positive integer, typically 3\(en5),
or -1 if the window is not XDnD-aware or the property could not be read.
.Sh SEE ALSO
.Xr x11dnd_set_aware 3 ,
.Xr x11dnd_version_at_least 3 ,
.Xr x11dnd 3
.Sh AUTHORS
.An alx@fastestcode.org
.Sh LICENSE
.Nm
is distributed under the X/MIT license.