.\" Copyright (C) 2025-2026 alx@fastestcode.org
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining
.\" a copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so, subject to
.\" the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.\" EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
.\" CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
.\" TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
.\" SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.Dd June 24, 2026
.Dt X11DND_UNREGISTER_TARGET 3
.Os
.Sh NAME
.Nm x11dnd_unregister_target
.Nd unregister a window as an XDnD drop target
.Sh LIBRARY
.Lb libx11dnd
.Sh SYNOPSIS
.In x11dnd.h
.Ft void
.Fn x11dnd_unregister_target "Display *dpy" "Window win"
.Sh DESCRIPTION
.Fn x11dnd_unregister_target
removes the
.Li XdndAware
property from
.Fa win
and discards any pending target session associated with that window.
.Pp
After calling this function, the window will no longer receive XDnD
drop events.
Any
.Xr x11dnd_target_process_event 3
calls for events on this window will return 0.
.Sh RETURN VALUES
None.
.Sh SEE ALSO
.Xr x11dnd_register_target 3 ,
.Xr x11dnd 3
.Sh AUTHORS
.An alx@fastestcode.org
.Sh LICENSE
.Nm
is distributed under the X/MIT license.