# XFile FreeBSD Makefile

PREFIX ?= /usr/local
MANDIR = $(PREFIX)/man
SHAREDIR = $(PREFIX)/share/xfile
APPLRESDIR = $(PREFIX)/etc/X11/app-defaults

INCDIRS = -I/usr/local/include -I../libx11dnd/include
LIBDIRS = -L/usr/local/lib -L../libx11dnd

CFLAGS += -O2 -Wall

SHELL = sh

.include "common.mf"

# Set to APPDEFS_CORE for core fonts
APPDEFS = $(APPDEFS_XFT)

install: common_install
